name: god_life_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^2.3.2
  sqflite: ^2.2.8+4
  path: ^1.8.2
  intl: ^0.18.1
  table_calendar: ^3.0.9
  shared_preferences: ^2.1.1
  http: ^1.1.0
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^17.0.0
  fl_chart: ^1.0.0
  health: ^11.0.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/  # 👈 이 줄을 추가해주세요! (앞에 띄어쓰기 2칸)