// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrSgZXU248oHzfv2N4PrekRUgJEgv8jlw',
    appId: '1:610798691221:android:43e1c5ffcad09914000c9c',
    messagingSenderId: '610798691221',
    projectId: 'ryeo-7e8e6',
    databaseURL: 'https://ryeo-7e8e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ryeo-7e8e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4mKmxT8ndTUEG4xyMrmKh-pRePS77db0',
    appId: '1:610798691221:ios:17126c790e8faee0000c9c',
    messagingSenderId: '610798691221',
    projectId: 'ryeo-7e8e6',
    databaseURL: 'https://ryeo-7e8e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ryeo-7e8e6.firebasestorage.app',
    iosBundleId: 'com.jeonghyuck.godLifeAppNew',
  );
}
