platform :ios, '16.0' # 최소 버전 14 이상
$FirebaseSDKVersion = '10.25.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

 # ✅ Firebase 관련 pod 제거 또는 주석 처리
  # pod 'Firebase', :modular_headers => true
  # pod 'Firebase/Core', '~> 10.25.0'
  # pod 'FirebaseDatabase', '~> 10.25.0'
  # pod 'GoogleSignIn', '~> 8.0.0'
  # pod 'GoogleUtilities/UserDefaults', '~> 8.0.0'

  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# ❗️ 비모듈 오류 방지를 위한 핵심 코드
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # 👇 이것도 함께 유지
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end